#!/usr/bin/env sh
set -e

if [ -e /opt/vendor ]; then
    cp /opt/vendor /var/www/notifications/vendor -r
    chown breeze:breeze vendor -R
    composer setup
fi

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
