version: '3.8'

networks:
  production:
    name: production-overlay
    external: true


services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    networks:
      - production
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
