name: 'breezemm'

networks:
  staging:
    name: 'net'
    external: true

services:
  kong:
    image: 'kong:latest'
    container_name: 'breeze-kong-staging'
    environment:
      - 'KONG_DATABASE=off'
      - 'KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml'
      - 'KONG_PROXY_ACCESS_LOG=/dev/stdout'
      - 'KONG_ADMIN_ACCESS_LOG=/dev/stdout'
      - 'KONG_PROXY_ERROR_LOG=/dev/stderr'
      - 'KONG_ADMIN_ERROR_LOG=/dev/stderr'
      - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
      - 'KONG_LOG_LEVEL=debug'
      - 'KONG_PLUGINS=bundled'
    volumes:
      - './infra/kong/staging/config:/usr/local/kong/declarative'
      - './infra/kong/staging/logs/file.log:/file.log'
    networks:
      staging:
        ipv4_address: '172.16.101.4'
    ports:
      - '8000:8000'
      - '8001:8001'
    restart: 'unless-stopped'

  auth:
    build:
      context: './apps/auth'
      dockerfile: 'staging.dockerfile'
    container_name: 'breeze-auth-staging'
    env_file: './apps/auth/staging.env'
    networks:
      staging:
        ipv4_address: '172.16.101.5'
    restart: 'unless-stopped'
    
  posts:
    build:
      context: './apps/posts'
      dockerfile: 'staging.dockerfile'
    container_name: 'breeze-posts-staging'
    env_file: './apps/posts/staging.env'
    networks:
      staging:
        ipv4_address: '172.16.101.6'
    restart: 'unless-stopped'
