networks:
  development:
    driver: bridge
    name: development
    external: true

services:
  bun:
    build:
      dockerfile: infra/bun/Dockerfile
      context: .
    image: breezemm.com/bun:latest
    working_dir: /temp/dev

  auth:
    restart: unless-stopped
    image: breezemm.com/auth:latest
    deploy:
      replicas: 1
    build:
      args:
        APP_PATH: ./apps/auth
        WITH_HORIZON: "true"
      context: .
      dockerfile: Dockerfile
    environment:
      WITH_HORIZON: "true"
    networks:
      - development
    depends_on:
      - bun
    volumes:
      - ./apps/auth:/var/www/html/apps/auth
      - ./packages:/var/www/html/packages
    ports:
      - "8005:80"

  posts:
    restart: unless-stopped
    build:
      args:
        APP_PATH: ./apps/posts
      context: .
      dockerfile: Dockerfile
    environment:
      WITH_HORIZON: false
    networks:
      - development
    volumes:
      - ./apps/posts:/var/www/html/apps/posts
      - ./apps/posts/vendor:/var/www/html/apps/posts/vendor
      - ./packages:/var/www/html/packages
    ports:
      - "8006:80"



