version: '3.8'

networks:
  development:
    driver: bridge
    name: development
    external: true


services:
  bun:
    build:
      dockerfile: infra/bun/Dockerfile
      context: .
    image: breezemm.com/bun:latest
    working_dir: /temp/dev

  auth:
    restart: unless-stopped
    build:
      args:
        APP_PATH: ./apps/auth
      context: .
      dockerfile: Dockerfile
    environment:
      WITH_HORIZON: "true"
    networks:
      - development
    depends_on:
      - bun
    volumes:
      - ./apps/auth:/var/www/html/apps/auth
    ports:
      - "8003:80"

#  posts:
#    restart: unless-stopped
#    build:
#      args:
#        APP_PATH: ./apps/posts
#      context: .
#      dockerfile: not-working.Dockerfile
#    environment:
#      WITH_HORIZON: false
#    networks:
#      - development
#    volumes:
#      - ./apps/posts:/var/www/html/apps/posts
#    ports:
#      - "8004:80"
