version: '3.8'

networks:
  development:
    driver: bridge
    name: development
    external: true



services:
  bun:
    build:
      dockerfile: infra/bun/Dockerfile
      context: .
    image: breezemm.com/bun:latest
    working_dir: /temp/dev

  auth:
    restart: unless-stopped
    build:
      args:
        APP_PATH: ./apps/auth
      context: .
      dockerfile: Dockerfile
    networks:
      - development
    volumes:
      - ./apps/auth:/var/www/html/apps/auth
    ports:
      - "8003:80"

#  gateway:
#    restart: unless-stopped
#    build:
#      args:
#        APP_PATH: ./apps/gateway
#      context: .
#      dockerfile: Dockerfile
#    networks:
#      - development
#    volumes:
#      - ./apps/gateway:/var/www/html/apps/gateway
#    ports:
#      - "8003:8000"
#    depends_on:
#      - mysql
#
#  wallets:
#    restart: unless-stopped
#    build:
#      args:
#        APP_PATH: ./apps/wallets
#      context: .
#      dockerfile: Dockerfile
#    networks:
#      - development
#    volumes:
#      - ./apps/wallets:/var/www/html/apps/wallets
#    ports:
#      - "8003:8000"
#    depends_on:
#      - mysql
#
#  notifications:
#    restart: unless-stopped
#    build:
#      args:
#        APP_PATH: ./apps/notifications
#      context: .
#      dockerfile: Dockerfile
#    networks:
#      - development
#    volumes:
#      - ./apps/notifications:/var/www/html/apps/notifications
#    ports:
#      - "8003:8000"
#    depends_on:
#      - mysql
