name: 'breeze-staging'

networks:
  asn:
    name: 'asn240960291'
    ipam:
      driver: 'default'
      config:
        - subnet:   '192.0.69.0/24'
          ip_range: '192.0.69.0/24'
          gateway:  '192.0.69.254'

volumes:
  mysql:
  redis:

services:
  mysql:
    image: 'bitnami/mysql:8.0'
    container_name: 'mysql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p']
      retries: 3
      timeout: '5s'
    networks:
      asn:
        ipv4_address: '192.0.69.2'
    volumes:
      - 'mysql:/bitnami/mysql/data'
      - './infra/databases/mysql/init/01-databases.sql:/docker-entrypoint-initdb.d/create-db.sql'
    restart: 'unless-stopped'

  redis:
    image: 'bitnami/redis:7.2.4'
    container_name: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'ping']
      retries: 3
      timeout: '5s'
    networks:
      asn:
        ipv4_address: '192.0.69.3'
    volumes:
      - 'redis:/bitnami/redis'
    restart: 'unless-stopped'
