version: 3


tasks:

  prepare:
    cmd: docker create network development

  sh:*:
    vars:
      ARG_1: '{{index .MATCH 0}}'
    desc: "Start a shell in a service"
    cmd: docker compose exec {{.ARG_1}} sh

  build:
    desc: "Build or rebuild services"
    cmds:
      - docker compose build
      - docker compose -f docker-compose.base.yaml build
      - docker compose -f docker-compose.generator.yaml build


  up:base:
    desc: "Start all core service in background"
    preconditions:
      - docker inspect development
    cmd: docker compose -f docker-compose.base.yaml up -d

  up:generator:
    desc: "Start a service in background"
    cmd: docker compose -f docker-compose.generator.yml up -d

  stop:
    desc: "Stop services"
    cmds:
      - docker compose stop
      - docker compose -f docker-compose.base.yml stop
      - docker compose -f docker-compose.generator.yml stop
      - docker compose down --remove-orphans

  down:
    desc: "Stop and remove containers and networks"
    cmds:
      - docker compose down --remove-orphans
      - docker compose -f docker-compose.base.yml down --remove-orphans
      - docker compose -f docker-compose.generator.yml down --remove-orphans


  restart:
    desc: "Restart services"
    cmds:
      - docker compose restart
      - docker compose -f docker-compose.base.yml restart
      - docker compose -f docker-compose.generator.yml restart

  restart:*:
    vars:
      ARG_1: '{{index .MATCH 0}}'
    desc: "Restart a service"
    cmd: docker compose -f docker-compose.{{.ARG_1}}.yml restart

  ps:
    desc: "List containers"
    cmds:
      - docker compose ps
      - docker compose -f docker-compose.base.yml ps
      - docker compose -f docker-compose.generator.yml ps
