#!/usr/bin/env sh
set -e

if [ -e /opt/vendor ]; then
    cp /opt/vendor /var/www/gateway/vendor -r
    chown breeze:breeze vendor -R
    composer setup
fi

if [ ! -e /var/www/gateway/storage/oauth-private.key ] && [ ! -e /var/www/gateway/storage/oauth-public.key ]; then
    php artisan passport:install --force
fi

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
