#!/usr/bin/env sh
set -e

if [ -e /opt/vendor ]; then
  cp /opt/vendor /var/www/wallets/vendor -r
  chown breeze:breeze vendor -R
  composer setup
else
  php artisan migrate
fi

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
