ARG PHP_VERSION
ARG FRANKEN_VERSION
FROM dunglas/frankenphp:${FRANKEN_VERSION}-php${PHP_VERSION}-alpine

RUN apk add --update --no-cache --virtual .persistent-deps \
    supervisor

RUN install-php-extensions \
    gd \
    # opcache \ TODO: fix segmentation fault (core dumped)
    exif \
    zip \
    sockets \
    pdo_mysql \
    pcntl \
    rdkafka \
    redis

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    php -r "unlink('composer-setup.php');"

COPY octane.ini /usr/local/etc/php/conf.d/
