FROM breeze/php:latest as builder

WORKDIR /var/www/wallets

COPY composer.json .
COPY composer.lock .

RUN composer install \
    --no-autoloader && \
    composer dump-autoload --optimize --no-scripts


FROM breeze/php:latest

WORKDIR /var/www/wallets

RUN adduser -D -u 1000 -g '' breeze && \
    chown -R breeze:breeze /home/breeze

COPY --chown=breeze:breeze . .
COPY --chown=breeze:breeze --from=builder /var/www/wallets/vendor /opt/vendor
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY docker/start-container /usr/local/bin/start-container

RUN chmod +x /usr/local/bin/start-container

ENTRYPOINT ["start-container"]
