/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthenticatedWalletIndexImport } from './routes/_authenticated/wallet/index'
import { Route as AuthenticatedVerifyIndexImport } from './routes/_authenticated/verify/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedWalletIndexRoute = AuthenticatedWalletIndexImport.update({
  path: '/wallet/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedVerifyIndexRoute = AuthenticatedVerifyIndexImport.update({
  path: '/verify/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/verify/': {
      preLoaderRoute: typeof AuthenticatedVerifyIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/wallet/': {
      preLoaderRoute: typeof AuthenticatedWalletIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([
    AuthenticatedIndexRoute,
    AuthenticatedVerifyIndexRoute,
    AuthenticatedWalletIndexRoute,
  ]),
  AuthLoginRoute,
])

/* prettier-ignore-end */
