_format_version: "3.0"
_transform: true

services:
  - host: auth
    name: auth_service
    url: http://auth:8000/api/v1
    port: 8000
    protocol: http
    routes:
      - name: auth_route
        paths:
          - /api/v1/auth
        strip_path: true


