CREATE DATABASE IF NOT EXISTS `auth`;
# CREATE DATABASE IF NOT EXISTS `gateway`;
# CREATE DATABASE IF NOT EXISTS `wallet`;
# CREATE DATABASE IF NOT EXISTS `notification`;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
