import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { IntersectorProvider } from "@/context/interSectorContext";
import { WrapContextComponent } from "@/components/ContextProviderWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`inter.className`}>
        <WrapContextComponent>
          <NavBar />
          <div className="pb-[168px] pe-6 ps-6 pt-[152px] md:pb-[260px] md:pe-[145px] md:ps-36 md:pt-[188px]">
            {children}
          </div>
          <Footer />
        </WrapContextComponent>
      </body>
    </html>
  );
}
