#!/usr/bin/env sh
set -e

pnpm install
composer install
php artisan key:generate
php artisan migrate:fresh
php artisan passport:install

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
