version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
      open-pull-requests-limit: 10
      commit-message:
        prefix: "chore(npm): update"
        include: "dependencies"
        exclude: "devDependencies"



  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      open-pull-requests-limit: 10
      commit-message:
        prefix: "chore(docker): update"
        include: "dependencies"
        exclude: "devDependencies"

  # Enable version updates for php
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      open-pull-requests-limit: 10
      commit-message:
        prefix: "chore(composer): update"
        include: "dependencies"
        exclude: "devDependencies"
