name: Deploy to Server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_DIR: /prod/git/repo/breeze
        REPO_URL: git@github.com-breeze:myanmarcyberyouths/breeze
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'

          cd /prod/git/repo/breeze || exit

          if [ -d ".git" ]; then
            git pull
          else
            git clone git@github.com-breeze:myanmarcyberyouths/breeze .
          fi

          docker compose -f staging.compose.yaml up -d --build mysql redis

        EOF
